import JSZip from "jszip";

interface ExportOptions {
  title: string;
  prompt?: string;
  generatedCode: string;
}

export function sanitizeFileName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

// Strip markdown code fences like ```tsx ... ``` or ```jsx ... ```
export function cleanCode(code: string): string {
  let cleaned = code.trim();
  if (cleaned.startsWith("```")) {
    const lines = cleaned.split("\n");
    if (lines[0].startsWith("```")) {
      lines.shift();
    }
    if (lines[lines.length - 1].startsWith("```")) {
      lines.pop();
    }
    cleaned = lines.join("\n");
  }
  return cleaned;
}

export function buildExportFiles({ title, prompt, generatedCode }: ExportOptions): Record<string, string> {
  const code = cleanCode(generatedCode);
  
  const packageJson = JSON.stringify({
    name: sanitizeFileName(title),
    private: true,
    version: "0.0.0",
    type: "module",
    scripts: {
      dev: "vite",
      build: "vite build",
      lint: "eslint .",
      preview: "vite preview"
    },
    dependencies: {
      react: "^19.0.0",
      "react-dom": "^19.0.0",
      "lucide-react": "^0.468.0",
      "clsx": "^2.1.1",
      "tailwind-merge": "^2.5.5"
    },
    devDependencies: {
      "@eslint/js": "^9.15.0",
      "@types/react": "^19.0.0",
      "@types/react-dom": "^19.0.0",
      "@vitejs/plugin-react": "^4.3.4",
      eslint: "^9.15.0",
      "eslint-plugin-react": "^7.37.2",
      "eslint-plugin-react-hooks": "^5.0.0",
      "eslint-plugin-react-refresh": "^0.4.14",
      globals: "^15.12.0",
      vite: "^6.0.1",
      tailwindcss: "^4.0.0",
      "@tailwindcss/vite": "^4.0.0"
    }
  }, null, 2);

  const viteConfig = `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), tailwindcss()],
})
`;

  const indexHtml = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>✨</text></svg>" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
  </head>
  <body class="bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100">
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`;

  const mainJsx = `import React from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import './index.css'

createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
`;

  const indexCss = `@import "tailwindcss";

body {
  margin: 0;
  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
}
`;

  const readmeMd = `# ${title}

Generated by **CraftSite AI** — a premium AI website builder.

${prompt ? `### Original Prompt\n> ${prompt}\n` : ""}

## Getting Started

### 1. Install dependencies
\`\`\`bash
npm install
\`\`\`

### 2. Run the development server
\`\`\`bash
npm run dev
\`\`\`

### 3. Build for production
\`\`\`bash
npm run build
\`\`\`
`;

  return {
    "package.json": packageJson,
    "vite.config.js": viteConfig,
    "index.html": indexHtml,
    "src/main.jsx": mainJsx,
    "src/App.jsx": code,
    "src/index.css": indexCss,
    "README.md": readmeMd,
  };
}

export async function exportProjectAsZip(options: ExportOptions): Promise<void> {
  if (!options.generatedCode) {
    throw new Error("No generated code available to export.");
  }

  const zip = new JSZip();
  const files = buildExportFiles(options);

  // Add files to zip
  Object.entries(files).forEach(([path, content]) => {
    zip.file(path, content);
  });

  const content = await zip.generateAsync({ type: "blob" });
  
  // Download using browser Blob URLs (avoids needing file-saver dependency)
  const url = URL.createObjectURL(content);
  const a = document.createElement("a");
  a.href = url;
  a.download = `craftsite-${sanitizeFileName(options.title)}.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
