import "dotenv/config";
import { z } from 'zod';

const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
  PORT: z.string().optional().default('5000'),
  DATABASE_URL: z.string().url(),
  JWT_SECRET: z.string().min(10),
  CLIENT_URL: z.string().url(),
  CLIENT_URLS: z.string().optional(),
  FRONTEND_URL: z.string().url().optional(),
  API_URL: z.string().url().optional(),
  BACKEND_URL: z.string().url().optional(),
  OPENROUTER_API_KEY: z.string().optional(),
  GEMINI_API_KEY: z.string().optional(),
  AI_PROVIDER: z.enum(["auto", "openrouter", "gemini", "groq", "together", "mistral", "mock"]).optional().default("auto"),
  AI_MODE: z.enum(["balanced", "fast", "quality", "free", "code"]).optional().default("balanced"),
  ALLOW_MOCK_FALLBACK: z.string().optional().transform((val) => val === "true"),
  OPENROUTER_MODEL: z.string().optional().default("qwen/qwen3-coder:free"),
  GEMINI_MODEL: z.string().optional().default("gemini-2.5-flash"),
  OPENROUTER_FALLBACK_MODELS: z.string().optional(),
  GEMINI_FALLBACK_MODELS: z.string().optional().default("gemini-2.0-flash,gemini-2.0-flash-lite,gemini-1.5-flash"),
  OPENROUTER_SITE_URL: z.string().optional().default("http://localhost:3000"),
  OPENROUTER_APP_NAME: z.string().optional().default("CraftSite AI"),
  GROQ_API_KEY: z.string().optional(),
  GROQ_MODEL: z.string().optional().default("llama-3.3-70b-versatile"),
  GROQ_FALLBACK_MODELS: z.string().optional(),
  TOGETHER_API_KEY: z.string().optional(),
  TOGETHER_MODEL: z.string().optional().default("meta-llama/Llama-3.3-70B-Instruct-Turbo"),
  TOGETHER_FALLBACK_MODELS: z.string().optional(),
  MISTRAL_API_KEY: z.string().optional(),
  MISTRAL_MODEL: z.string().optional().default("mistral-large-latest"),
  MISTRAL_FALLBACK_MODELS: z.string().optional(),
  AI_REQUEST_TIMEOUT_MS: z.string().optional().default("90000").transform((val) => parseInt(val) || 90000),
  AI_EDIT_TIMEOUT_MS: z.string().optional().default("60000").transform((val) => parseInt(val) || 60000),
  AI_MAX_RETRIES: z.string().optional().default("1").transform((val) => parseInt(val) || 1),
  RAZORPAY_KEY_ID: z.string().optional(),
  RAZORPAY_KEY_SECRET: z.string().optional(),
  RAZORPAY_WEBHOOK_SECRET: z.string().optional(),
  GOOGLE_CLIENT_ID: z.string().optional(),
  GOOGLE_CLIENT_SECRET: z.string().optional(),
  GOOGLE_REDIRECT_URI: z.string().optional(),
  GITHUB_CLIENT_ID: z.string().optional(),
  GITHUB_CLIENT_SECRET: z.string().optional(),
  GITHUB_REDIRECT_URI: z.string().optional(),
  FRONTEND_AUTH_ERROR_URL: z.string().optional(),
  FRONTEND_AUTH_SUCCESS_URL: z.string().optional(),
});

export const env = envSchema.parse(process.env);
