import { Router } from "express";
import { z } from "zod";

export const generateRouter = Router();

const generateSchema = z.object({
  prompt: z.string().min(10, "Prompt must be at least 10 characters"),
  style: z.string().optional(),
  websiteType: z.string().optional(),
});

generateRouter.post("/", async (req, res) => {
  const result = generateSchema.safeParse(req.body);

  if (!result.success) {
    return res.status(400).json({
      success: false,
      message: "Invalid request body",
      errors: result.error.flatten().fieldErrors,
    });
  }

  const { prompt, style, websiteType } = result.data;

  return res.json({
    success: true,
    message: "Website generation endpoint working",
    data: {
      prompt,
      style: style || "modern",
      websiteType: websiteType || "landing-page",
      generatedCode: `
export default function GeneratedWebsite() {
  return (
    <main className="min-h-screen bg-slate-950 text-white">
      <section className="mx-auto max-w-5xl px-6 py-24 text-center">
        <h1 className="text-5xl font-black">
          Generated by CraftSite AI
        </h1>
        <p className="mt-6 text-white/60">
          ${prompt}
        </p>
      </section>
    </main>
  );
}
      `.trim(),
    },
  });
});
